agent_former_base: '/home/hpc/hpcguest4/ActiveLoopProject/animated-octo-potato'

result_dir: 'agentformer-result'

python_path: 'singularity exec --nv /home/hpc/hpcguest4/sifs/hlsix-220922.sif /opt/conda/envs/torch/bin/python3'
training_script: 'model_train.py'
save_latent_script: 'latent_gen.py'
