default: &DEFAULT
  adapter: postgresql
  database: storage_parameter
  username: myapp
  password: password1
  pool: 50
  timeout: 1000
  host: localhost

test:
  <<: *DEFAULT
  adapter: sqlite3
  database: '/tmp/test.sqlite3'
