steersuite_exec_base: "/home/kaidong/SteerSuite-P2/build/bin"
steersuite_exec_cmd: "./steersim -commandline -config minimal.xml"
steersuite_record_pool: "steersimRecord-tmp"
steersuite_process_pool: "steersimRecord-tmp-processed"
