steersuite_exec_base: "/home/hpc/hpcguest4/ActiveLoopProject/SteerSuite-P2/build/bin"
steersuite_exec_cmd: "singularity exec --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH --nv /home/hpc/hpcguest4/sifs/hlsix-220922.sif ./steersim -commandline -config minimal.xml"
steersuite_record_pool: "steersimRecord-tmp"
steersuite_process_pool: "steersimRecord-tmp-processed"
